version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: grimdank-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: grimdank_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - grimdank-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: grimdank-backend-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/grimdank_db?authSource=admin
      DATABASE_NAME: grimdank_db
      SERVER_PORT: 8080
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - grimdank-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grimdank-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - grimdank-network

volumes:
  mongodb_data:

networks:
  grimdank-network:
    driver: bridge
